# Node.js compatibility | Cloudflare Workers docs https://developers.cloudflare.com/workers/runtime-apis/nodejs/
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "test-db"
database_id = "662acbe4-31f1-4c53-92e1-ee04499a1916"
